### ISSUE TITLE
Gemini L2 issue

### ISSUE THREAD

**Issue by nateGeorge** [bmoscon/cryptofeed#128] opened 2019-07-31 02:36 UTC
When using cryptostore with Gemini to get L2 data for BTC-USD, the following error appears:

```python
2019-07-30 20:32:02,358 : INFO : Collector for GEMINI running on PID 3744
Process Collector-1:6:
Traceback (most recent call last):
  File "/home/nate/anaconda3/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/home/nate/anaconda3/lib/python3.6/site-packages/cryptostore/collector.py", line 64, in run
    fh.add_feed(self.exchange, book_interval=window, config=self.exchange_config, callbacks=cb)
  File "/home/nate/anaconda3/lib/python3.6/site-packages/cryptofeed-1.0.0-py3.6.egg/cryptofeed/feedhandler.py", line 78, in add_feed
    self.feeds.append(_EXCHANGES[feed](**kwargs))
  File "/home/nate/anaconda3/lib/python3.6/site-packages/cryptofeed-1.0.0-py3.6.egg/cryptofeed/gemini/gemini.py", line 26, in __init__
    if len(pairs) != 1:
TypeError: object of type 'NoneType' has no len()
```

Seems like from their API page L2 data is supported: https://docs.gemini.com/rest-api/#current-order-book

I'm using Redis with Arctic to store the data.

**Comment by xiandong79** [comment] 2019-08-01 01:41
what is your config? 
Besides,  Gemini only supports one pair for each WebSocket connection.

**Comment by bmoscon** [comment] 2019-08-01 01:48
Gemini not supported on cryptostore due to #91, so this is really a dupe of that issue

**Closed by bmoscon** 2019-08-01 01:48 UTC
