### ISSUE TITLE
Latency for handling book messages increasing in time with max_depth

### ISSUE THREAD

**Issue by alekiv** [bmoscon/cryptofeed#406] opened 2021-02-01 11:08 UTC
I'm getting Binance book data and I have a question about latency increase for handle book messages in time.
When I start Cryptofeed, latency is ~0.5ms, however, right after that, it starts to go up and continue increasing. If I restart it, it is low again.

![image](https://user-images.githubusercontent.com/9446663/106450411-3612b600-6496-11eb-97f7-57341dd2187a.png)

right after start:
time() - receipt_timestamp = 0.425339ms
time() - timestamp = 116.597176ms

after 12 hours of running script:
time() - receipt_timestamp = **4.936695ms**
time() - timestamp = 122.044802ms

Any explanation for this?

Behavior is reproduced on two separate servers.
Script for reproducing:
```
#!/usr/bin/env python3

from time import time
from cryptofeed.callback import BookCallback
from cryptofeed import FeedHandler
from cryptofeed.exchanges import Binance
from cryptofeed.defines import L2_BOOK


async def book(feed, pair, book, timestamp, receipt_timestamp):
    time_now = time()
    receipt_timestamp_age = (time_now - receipt_timestamp) * 1000
    exchange_timestamp_age = (time_now - timestamp) * 1000
    print(f"time() - receipt_timestamp = {receipt_timestamp_age:.6f}ms")
    print(f"time() - timestamp = {exchange_timestamp_age:.6f}ms")


def sub_to_feed():
    f = FeedHandler()
    f.add_feed(
        Binance(
            max_depth=30,
            pairs=["BTC-USDT", "ETH-USDT"],
            channels=[L2_BOOK],
            callbacks={L2_BOOK: BookCallback(book)},
        )
    )
    f.run()


def main():
    sub_to_feed()


if __name__ == "__main__":
    main()
```
cryptofeed: v1.6.2
python: v3.9.0 and v3.8.5

**Comment by bmoscon** [comment] 2021-02-01 23:07
I tested on the latest version in master, I get very different values. I'm not sure what hardware you are using, or if the differences are attributed to the version difference, or OS differences, so can you try on the latest in master and see if it changes dramatically? also, using depth= can add latency because a new book needs to be created and returned to the user. When I ran, I ran this:

```python
from time import time
from cryptofeed.callback import BookCallback
from cryptofeed import FeedHandler
from cryptofeed.exchanges import Binance
from cryptofeed.defines import L2_BOOK, BOOK_DELTA


counter = 0

async def book(timestamp, receipt_timestamp, **kwargs):
    global counter
    counter += 1
    if counter == 100:
        counter = 0
        time_now = time()
        receipt_timestamp_age = (time_now - receipt_timestamp) * 1000
        exchange_timestamp_age = (time_now - timestamp) * 1000
        print(f"time() - receipt_timestamp = {receipt_timestamp_age:.6f}ms")
        print(f"time() - timestamp = {exchange_timestamp_age:.6f}ms")


def sub_to_feed():
    f = FeedHandler()
    f.add_feed(Binance(symbols=["BTC-USDT", "ETH-USDT"], channels=[L2_BOOK], callbacks={L2_BOOK: book, BOOK_DELTA: book}))
    f.run()


def main():
    sub_to_feed()


if __name__ == "__main__":
    main()
```


timestamp is the timestamp from the exchange, receipt timestamp is the time that the message comes out of the websocket. I'm not really sure how time - receipt could be so large, but time - timestamp could remain consistent. I ran for about an hour and while the timestamps did have small fluctuations, the average for the hour was:

time() - receipt_timestamp = 0.113010ms
time() - timestamp = 25.800943ms

**Comment by alekiv** [comment] 2021-02-02 11:10
> I tested on the latest version in master, I get very different values. I'm not sure what hardware you are using, or if the differences are attributed to the version difference, or OS differences, so can you try on the latest in master and see if it changes dramatically?

Thanks for testing it. Will also test additional scenarios.

**Comment by alekiv** [comment] 2021-02-02 22:01
tests results:
```
    f = FeedHandler()
    f.add_feed(
        Binance(
            max_depth=30,
            pairs=["BTC-USDT", "ETH-USDT"],
            channels=[L2_BOOK],
            callbacks={L2_BOOK: BookCallback(book)},
        )
    )
    f.run()
```
![image](https://user-images.githubusercontent.com/9446663/106667522-14aaea80-65ba-11eb-8049-c651a3bf2d00.png)

```
    f = FeedHandler()
    f.add_feed(
        Binance(
            pairs=["BTC-USDT", "ETH-USDT"],
            channels=[L2_BOOK],
            callbacks={L2_BOOK: book, BOOK_DELTA: book},
        )
    )
    f.run()
```
![image](https://user-images.githubusercontent.com/9446663/106667678-47ed7980-65ba-11eb-8811-ea722d1123ac.png)

```
    f = FeedHandler()
    f.add_feed(
        Binance(
            max_depth=30,
            pairs=["BTC-USDT", "ETH-USDT"],
            channels=[L2_BOOK],
            callbacks={L2_BOOK: book, BOOK_DELTA: book},
        )
    )
    f.run()
```
![image](https://user-images.githubusercontent.com/9446663/106667784-71a6a080-65ba-11eb-83f9-b041d1fb72ed.png)


```
    f = FeedHandler()
    f.add_feed(
        Binance(
            pairs=["BTC-USDT", "ETH-USDT"],
            channels=[L2_BOOK],
            callbacks={L2_BOOK: BookCallback(book)},
        )
    )
    f.run()
```
![image](https://user-images.githubusercontent.com/9446663/106667899-97cc4080-65ba-11eb-87eb-336a39ac2207.png)

As I can see that **max_depth=30** triggers book messages handling time increase. Important part that it keeps increasing in time.
@bmoscon, is it still worth to try master? Are any related changed there?

**Comment by bmoscon** [comment] 2021-02-02 23:55
I am surprised it continually increases, but max_depth is having to do extra processing on the book to truncate it, so its not totally unexpected that it will increase the latency vs non truncated books. The code on master does have some performance improvements, but I wouldnt expect this to be wholly resolved. My new order book code will make this a lot faster (once its completed). I'll leave this open until I've migrated to the new orderbook and then I can have another look at it. I'd expect larger latency overall, but nothing that is slowly increasing forever.

**Comment by Dynamikey** [comment] 2021-02-03 09:48
@alekiv may I ask what you used to graph your results? Did you use matplotlib or something like grafana?

**Comment by alekiv** [comment] 2021-02-03 19:24
> @alekiv may I ask what you used to graph your results? Did you use matplotlib or something like grafana?

it is Grafana

**Comment by zhenpingfeng** [comment] 2021-02-20 14:59
I have this problem for a long time too. The latency keeps increasing, sometimes even more than several minutes.

**Comment by bmoscon** [comment] 2021-02-21 16:07
@zhenpingfeng I'm actively working on several improvements that will reduce the book processing time (which adds this latency) by 80%+

**Comment by Dynamikey** [comment] 2021-02-21 21:34
@bmoscon May I ask what’s exactly causing this latency increase here pls? Also, what methods are you using to reduce the processing time? Thanks

**Comment by bmoscon** [comment] 2021-02-21 21:40
for some exchanges and some trading pairs you have have over 1000 updates a second on an orderbook. Processing that data takes time, and for some scenarios, you cant process the messages faster than they are received. Since most the issue is with Python being slow (relatively speaking, when compared to compiled languages) I'm experimenting with Cython and C implementations for these pain points. I have an orderbook in C already thats significantly faster for storing the updates, but the message parsing and processing takes some time too, so working on that area as well.

**Comment by bmoscon** [comment] 2021-02-24 00:44
For those interested, see https://github.com/bmoscon/cryptofeed/discussions/420#discussioncomment-399654

**Comment by zhenpingfeng** [comment] 2021-03-07 11:00
> For those interested, see [#420 (comment)](https://github.com/bmoscon/cryptofeed/discussions/420#discussioncomment-399654)

Nice result, my pure rust implementation is about 23µs with depth 20 order book on 2.8Ghz cascade lake intel CPU.

**Comment by zhenpingfeng** [comment] 2021-03-09 07:19
@bmoscon Should we replace std zlib with [deflate](https://pypi.org/project/deflate/)? It's a [libdeflate](https://github.com/ebiggers/libdeflate) python wrapper. In my test, deflate is faster than std zlib 24% with depth 20 order book.

**Comment by bmoscon** [comment] 2021-09-05 00:54
I've completed the change over to using the C orderbook code, so closing this

**Closed by bmoscon** 2021-09-05 00:54 UTC
Labels: question
