### ISSUE TITLE
l2 order book data for some exchanges is inconsistent (ask and bid prices overlap)

### ISSUE THREAD

**Issue by joelrich** [bmoscon/cryptofeed#232] opened 2020-04-07 10:35 UTC
I have written a function to reconstruct order books from recorded order book data and found that it is inconsistent for some exchanges.

This is how I persist the data:
```python
            batch_row = dict(timestamp=timestamp, delta=delta)
            for side in [BID, ASK]:
                entries = data.get(side, [])
                if isinstance(entries, dict):
                    entries = entries.items()

                batch_row[f"{side}_prices"] = " ".join(to_str(price) for price, size in entries)
                batch_row[f"{side}_sizes"] = " ".join(to_str(size) for price, size in entries)
            self.writer.append(self.exchange, pair, L2_BOOK + "_batch", store_timestamp, batch_row)
```
When I read the data, I perform the following check:
```python
        nonzero_bid_prices = col_bid_prices[i][col_bid_sizes[i] > 0]
        nonzero_ask_prices = col_ask_prices[i][col_ask_sizes[i] > 0]
        if min(len(nonzero_bid_prices), len(nonzero_ask_prices)) > 0:
            assert np.max(nonzero_bid_prices) < np.min(nonzero_ask_prices), "data inconsistent"
```
This check ensures that the snapshot/delta does not contain overlapping prices.
Unfortunately, it fails for some exchanges, e.g. Bitmex. Here is an example:

```
Time: 2020-03-12 23:42:21.158979416
Delta: False
Bid prices: 0.5 1 1.5 2 3 3.5 4 5 5.5 1 10.5 11.5 16.5 23 31 32 33 ... 4630.5 4631 4631.5 4633 4633.5 4634.5
Ask prices: 464 4640.5 4641.5 4642 4642.5 4644.5 4645 4645.5 ... 600884.5 666666 993 999998 999999 1
```
There are two problematic ask prices: 464 (this is not a typo) and 1 (after 999999)

To prevent such problems, I think a similar check should run after retrieving order book data. If asks and bids overlap, the order book should be discarded followed by a reconnect/re-initialization of the order book.

**Comment by joelrich** [comment] 2020-04-13 10:38
@bmoscon what is your opinion on this issue? Personally, I find it worrisome that there is no guarantee for some weak consistencies (e.g. bid and ask do not overlap). If only a single websocket message is lost for whatever reason, this may affect all snapshots until the process is restarted.

**Comment by bmoscon** [comment] 2020-04-15 00:39
Its not something I've ever observed, but it will depend on the exchange most likely. Some have sequence numbers, so those will reconnect if a message is missing. Could be a case where messages are being lost due to queue sizes in websockets, so could up that to see if it improves.

**Comment by joelrich** [comment] 2020-04-15 06:38
Where is the queue size configured?

Yeah, I agree that this most likely only happens with some exchanges. I will analyze all my data at some point and will then provide a list of the affected exchanges.

Do you think it would be a good idea to check if the asks and bids are overlapping? I would suggest the following: Having a heapq for each order book side for the best prices. Then it is very cheap to test for overlaps in apply_depth. Would you accept a pull request for such a change?

**Comment by bmoscon** [comment] 2020-04-15 23:20
@joelrich its a param on connect:

https://github.com/bmoscon/cryptofeed/blob/master/cryptofeed/feedhandler.py#L202

the kwarg is `max_queue` and the default is 32.

https://websockets.readthedocs.io/en/stable/api.html

if the bids and asks overlap, the connection should be reset - but it could also be an exchange issue. eg, this was an issue on kraken for a while, but its since been fixed. In general though it should be considered as a data loss event, and the connection should be reset (and the book with it).  The prices are already ordered in the book, since its a sorted dictionary. No need to use any other data structure.

**Comment by joelrich** [comment] 2020-04-16 09:00
Ah, sorted dicts are even better. I will test the following check for a while:
```python
    def check_bid_ask_overlapping(self, book, pair):
        bid, ask = book[BID], book[ASK]
        assert isinstance(bid, sd) and isinstance(ask, sd)
        if len(bid) > 0 and len(ask) > 0:
            best_bid, best_ask = bid.keys()[-1], ask.keys()[0]
            if best_bid >= best_ask:
                raise BidAskOverlapping(f"best bid {best_bid} >= best ask {best_ask} for {pair}")
```

**Comment by joelrich** [comment] 2020-04-16 10:00
The first finding is that for UPBIT bid and ask are very often the same, e.g.:

```
cryptofeed.exceptions.BidAskOverlapping: best bid 39.2 >= best ask 39.2 for HBAR-KRW
```

**Comment by joelrich** [comment] 2020-04-16 13:29
Bittrex seems to be affected as well (but happened only once so far):
```
2020-04-16 15:03:10,096 : ERROR : BITTREX: encountered an exception, reconnecting
Traceback (most recent call last):
  File "/home/joel/.local/share/virtualenvs/cryptofeed2csv-gSWG8EAq/lib/python3.7/site-packages/crypto
    await self._handler(websocket, feed.message_handler, feed.uuid)
  File "/home/joel/.local/share/virtualenvs/cryptofeed2csv-gSWG8EAq/lib/python3.7/site-packages/crypto
    await handler(message, self.last_msg[feed_id])
  File "/home/joel/.local/share/virtualenvs/cryptofeed2csv-gSWG8EAq/lib/python3.7/site-packages/crypto
age_handler
    await self.book(data, timestamp)
  File "/home/joel/.local/share/virtualenvs/cryptofeed2csv-gSWG8EAq/lib/python3.7/site-packages/crypto
    await self.book_callback(self.l2_book[pair], L2_BOOK, pair, False, delta, timestamp, timestamp)
  File "/home/joel/.local/share/virtualenvs/cryptofeed2csv-gSWG8EAq/lib/python3.7/site-packages/crypto
    self.check_bid_ask_overlapping(book, pair)
  File "/home/joel/.local/share/virtualenvs/cryptofeed2csv-gSWG8EAq/lib/python3.7/site-packages/crypto
verlapping
    raise BidAskOverlapping(f"best bid {best_bid} >= best ask {best_ask} for {pair}")
cryptofeed.exceptions.BidAskOverlapping: best bid 192.77056951 >= best ask 192.74620241 for BSV-USDT
```

**Comment by joelrich** [comment] 2020-04-17 07:24
And also OKEX:
```
2020-04-17 07:45:31,796 : ERROR : OKEX: encountered an exception, reconnecting
cryptofeed.exceptions.BidAskOverlapping: best bid 171.01 >= best ask 171 for ETH-USD-SWAP
```

**Comment by bmoscon** [comment] 2020-04-21 00:08
I'll take a look into Bittrex this week, it could be I'm processing the messages incorrectly or there is some other bug for that exchange. it was a pain to implement because of the way it uses websockets, so let me take a look into that one

**Comment by joelrich** [comment] 2020-04-21 08:59
Cool, thanks! Bitfinex has also issues (but much less frequently):
```
Apr 20 12:14:39 he-cryptofeed-3 start.sh[16272]: cryptofeed.exceptions.BidAskOverlapping: BITFINEX ETH-EUR best bid 166.42 >= best ask 166.41
Apr 20 12:14:39 he-cryptofeed-3 start.sh[16272]: cryptofeed.exceptions.BidAskOverlapping: BITFINEX ETH-JPY best bid 19490 >= best ask 19489
```
Summary so far:
- Upbit is completely broken
- Bittrex has issues very frequently
- Bitfinex has issues infrequently
- Bitmex hasn't happened yet since I added the exception, but I know that there were issues in the past

**Comment by joelrich** [comment] 2020-04-23 09:44
Bitstamp & OKEx:
```
Apr 22 10:14:45 he-cryptofeed-3 start.sh[16272]: cryptofeed.exceptions.BidAskOverlapping: OKEX ETH-USD-200626 best bid 172.691 >= best ask 172.651
Apr 22 10:24:05 he-cryptofeed-3 start.sh[16272]: cryptofeed.exceptions.BidAskOverlapping: OKEX LTC-USD-SWAP best bid 41 >= best ask 41
Apr 22 10:24:07 he-cryptofeed-3 start.sh[16272]: cryptofeed.exceptions.BidAskOverlapping: OKEX ETH-USD-200626 best bid 173.061 >= best ask 173.037
Apr 22 11:14:43 he-cryptofeed-3 start.sh[16272]: cryptofeed.exceptions.BidAskOverlapping: BITSTAMP BTC-USD best bid 6973.69 >= best ask 6972.93
Apr 22 11:17:51 he-cryptofeed-3 start.sh[16272]: cryptofeed.exceptions.BidAskOverlapping: BITSTAMP BTC-USD best bid 6964.73 >= best ask 6964.67
```

**Comment by bmoscon** [comment] 2020-04-25 00:07
if you open a PR we can get this code in and at least have it reset books when they are bad. I can also do some testing to see if increasing the queue size will help. For individual exchanges I can look into any sequence numbers they provide (if any).

**Comment by joelrich** [comment] 2020-04-25 09:13
Here you go: https://github.com/bmoscon/cryptofeed/pull/240
For most exchanges, I do not expect that you can do anything else. One improvement would be to not reconnect, but only to re-initialize the orderbook (e.g. unsubscribe and then subscribe again --> new snapshot).

**Comment by vdbelt** [comment] 2020-04-25 14:48
In addition, some exchanges provide checksums/signatures for entire books. Im not sure what the resource costs of implementing such a verification check would be on every book update though. Perhaps we could make it a configuration option (on feed level?) as to what level of integrity is expected.

**Comment by joelrich** [comment] 2020-04-25 15:58
Personally, I think that's overkill. I would find a fast re-initialize (with subscribe & unsubscribe) more valuable. Then it could simply re-initialize every book every hour or so.

**Comment by Jay54520** [comment] 2020-06-07 12:55
> In addition, some exchanges provide checksums/signatures for entire books. Im not sure what the resource costs of implementing such a verification check would be on every book update though. Perhaps we could make it a configuration option (on feed level?) as to what level of integrity is expected.

I think this is a more rigorous solution. And is easy to achieve -- you just need to imitate the implementations on the exchanges' public library, such as [sequence number of  Huobi](https://github.com/HuobiRDCenter/huobi_Python/blob/7c26d1a2192adad5762b21ce071756174b1438e7/huobi/demo_service/mbp/mbp_data_process.py#L191)
```
if MbpDataFormat.sub_mbp_cache_pre.data.seqNum != mbp_event.data.prevSeqNum:  # the seq number mismatch and request again
                MbpDataFormat.reset_variables()
```

or [checksum of FTX](https://github.com/ftexchange/ftx/blob/356f07470647b6b6e4822b465c10f5254aa62213/websocket/client.py#L144)
```
if computed_result != checksum
```

**Comment by yohplala** [comment] 2020-06-26 10:43
Hello, it will not bring much, but error can be on the exchange itself.

It is a personal experience: I have been contributing 'manual market making' with a team of several people for a while on IDEX for a given pair.
Each one of us had some limit buy orders positioned in IDEX orderbook at same price level.
One day, we noticed, trades had been filled at price distinctly lower than that of our orders, BUT most of our orders were still in place. This is normally not what should have happened.

For me, the 'order matching engine' of the exchanges can also have failure.
This may be the root cause of the discrepancies you have in the order books as well.

**Comment by yohplala** [comment] 2020-06-27 16:28
Hello,
One question that may lead to a feature request, maybe be to be addressed into Cryptostore, instead of Cryptofeed.
Is there a tool to visualize in 'real time' data flowing through redis of kafka?
A 'simple' tool showing in a table data, most notably for trades and order books would help to compare with trades and order books from the exchanges.
In addition of being visible in the exchanges directly, GoCharting also make this data available (tab 'book').
So, even possible to avoid going in the exchanges one by one.
Such a tool would help checking data reception is good or not.
Is this existing?
Thanks for your feedback,
Bests,

**Comment by bmoscon** [comment] 2020-06-30 22:48
looks like kraken now has checksums as well, so that could be used to validate

**Comment by bmoscon** [comment] 2020-08-01 00:53
Basically this needs an exchange by exchange go over to double check that everything that can be validated is being validated. Some exchanges provide things like checksums and sequence numbers that can be used to validate orderbooks.

**Comment by bmoscon** [comment] 2020-08-24 23:42
deribit sequence number validation for books added

**Comment by bmoscon** [comment] 2020-08-25 00:06
I create #285 to track this. Once complete I'll add a page to the docs with information about this, how to enable verification, which books support seq #s, etc.

**Comment by bmoscon** [comment] 2020-11-29 21:01
all supported exchanges have been checked and verified against the docs, seq number and checksum validation has been done when supported. New doc was added that lists out what exchanges support what. Closing this.

**Closed by bmoscon** 2020-11-29 21:01 UTC
Labels: Major, Partially Complete, bug, help wanted
