### ISSUE TITLE
OHLCV calculation problem

### ISSUE THREAD

**Issue by uranuse2019** [bmoscon/cryptofeed#454] opened 2021-03-30 07:21 UTC
**Describe the bug**
there some structural issue with OHLCV calculation method
first of all, OLCV calculate based on trade timestamp, but in cryptofeed code, it's check the local server time and start to counting according to time windows. so the generated data is not usable because cryptofeed create candle different from exchange.

 the correct procedure is:
1- check the trade timestamp
2- start time is started from 00:00:00 UTC (as an example)
3- first trade with timestamp equaled or grater than above is open
4- the candle close on 00:00:59
5- the last trade with time stamp  equaled or less than above is close
6- High and low is clear 

please take care

**Comment by yohplala** [comment] 2021-03-30 07:34
Hi, it is a bit more tricky than that actually.
- you should keep in a buffer the last candle till it is not finished.
- each storage interval, you release all candles, even the last not finished one
- user has then to take care that candles issued by cryptostore overwrite previous ones if they share same timestamp & same timeframe

This last part is the tricky one I think. For each storage, one should review what is appropriate.
For parquet files, I think we ought to leave the duplicates one and leave the user manage the topic by himself/herself when he further process parquet files.
For the other storage like Arctic... I don't know if there is an 'easy way' of removing duplicates when adding them?

**Comment by yohplala** [comment] 2021-03-30 07:35
and you should check about the case when storage interval is lower than candle timeframe
There is no reason it would not work. Just a check

**Comment by uranuse2019** [comment] 2021-03-30 08:19
@yohplala 
it is need more than one candle in buffer. according to my experience  10 candle is more safe (1m interval).
but the base of OHLCV calculation in cryptofeed is not correct.

**Comment by yohplala** [comment] 2021-03-30 09:15
@uranuse2019 

> according to my experience 10 candle is more safe

Could you please elaborate? To what 'trouble' keeping 9 finished candles that will not change any longer does it answer?
(or I am not understanding something)

**Comment by bmoscon** [comment] 2021-03-31 22:54
if the exchange supports candles there is no reason to use this code, it was intended as an example of a how to for using an aggregator callback. There could be issues

**Comment by uranuse2019** [comment] 2021-04-01 20:47
@bmoscon thanks for your clarification 
I just shared my experience.
in addition creating candles based on live data is very useful for traders.
THX

**Comment by bmoscon** [comment] 2021-04-01 22:01
@uranuse2019 - if there is a bug, theres no reason to close this. I'm just recommending the use of the candles if they exist for the exchange in question.

**Comment by uranuse2019** [comment] 2021-04-03 06:51
@bmoscon as you explained above "it was intended as an example of a how to for using an aggregator callback. There could be issues" so I just warn any one who want to use this part of project (specially High frequency traders) be aware those problem explained above. me and my team trying to  optimize the code.
Also this is great project @bmoscon. we are really appreciate you.

**Comment by bmoscon** [comment] 2021-05-26 12:44
going to close this. A comment was added to the code, more exchanges support candles now, and the VWAP issue mentioned above is incorrect in my opinion. Maybe thats how Binance calculates and reports it, but thats not the standard way to calculate VWAP

**Closed by bmoscon** 2021-05-26 12:44 UTC
Labels: bug

**Comment by svabra** [comment] 2022-02-16 20:23
> if the exchange supports candles there is no reason to use this code, it was intended as an example of a how to for using an aggregator callback. There could be issues

Why should OHLCV not be used as such - if one wants to save storage i.e. never wants to save all the trades (e.g. only candles for 1m) , it does make sense to use OHLCV instead of `f.add_feed(Binance(candle_closed_only=False, channels=[CANDLES], symbols=['BTC-USDT'], callbacks=cbs_candles))`

Or do CANDLES offer a way to aggregate by window size? Let's say 1 minute. Would be meaningful to have it as optional parameter/arg. Would that contradict with the architect's idea? I'm thinking about creating a push request.

Also, thanks from my side. great work.

**Comment by bmoscon** [comment] 2022-02-16 21:05
you can use OHLCV if you want to, but there is no guarantee it will match what the exchange provides on their candles channel. You can specify the candle interval, its a kwarg the same way candle_closed_only is
