### ISSUE TITLE
Throw error when add feed and run with more than 200 symbols 

### ISSUE THREAD

**Issue by sc0Vu** [bmoscon/cryptofeed#818] opened 2022-04-09 09:42 UTC
Hi there,

Thanks for this cool library. I'd want to watch binance trades with more than 200 symbols, but I got these error:

```
Traceback (most recent call last):
  File "/sc0vu/test.py", line 71, in <module>
    main()
  File "/sc0vu/test.py", line 67, in main
    f.run()
  File "/cryptofeed/feedhandler.py", line 143, in run
    feed.start(loop)
  File "/cryptofeed/feed.py", line 289, in start
    for conn, sub, handler, auth in self.connect():
  File "/cryptofeed/feed.py", line 211, in connect
    ret.append((WSAsyncConn(addr, self.id, authentication=auth, subscription=filtered_sub, **endpoint.options), self.subscribe, self.message_handler, self.authenticate))
  File "/cryptofeed/connection.py", line 300, in __init__
    if not address.startswith("wss://"):
AttributeError: 'list' object has no attribute 'startswith'
Exception ignored in: <function AsyncConnection.__del__ at 0x10cd901f0>
Traceback (most recent call last):
  File "/cryptofeed/connection.py", line 91, in __del__
    if self.is_open:
  File "/cryptofeed/connection.py", line 308, in is_open
    return self.conn and not self.conn.closed
AttributeError: 'WSAsyncConn' object has no attribute 'conn'
```

After deep trace source code, I found the `addr = self._address()` will be array when the symbols is more than 200. Was there limit settings in this library?

Thanks!

**Comment by bmoscon** [comment] 2022-04-12 22:25
this is a duplicate of #808

**Closed by bmoscon** 2022-04-12 22:25 UTC
Labels: question
