### ISSUE TITLE
Binance futures now has stream limit 200

### ISSUE THREAD

**Issue by OnlyC** [bmoscon/cryptofeed#328] opened 2020-11-13 14:54 UTC
**Describe the bug**
Binance futures now has 200 stream limit (2020-10-27)
https://binance-docs.github.io/apidocs/futures/en/#change-log

**To Reproduce**
Use pairs=binance_futures_pairs() the app will freeze without getting any update. I have to make an array of SYMBOLS and remove some from the full list. Full list has 216 symbols.

**Comment by GoldenNaim** [comment] 2020-11-19 08:27
Hello,

I just trying to reproduce the bug, it works fine for me, binance_futures_pairs() return all pairs with this simple code :
```python
from decimal import Decimal
from cryptofeed.exchanges import BinanceFutures
from cryptofeed.pairs import binance_futures_pairs



def main():
```
    pairs=binance_futures_pairs()
    print(pairs)

if __name__ == '__main__':
    main()

**Comment by OnlyC** [comment] 2020-11-19 08:30
I mean it will freeze when you use in like: `add_feed(pairs=binance_futures_pairs())` & `feed.run()`.

**Comment by GoldenNaim** [comment] 2020-11-19 08:31
Okay, I will try to see what happened my crypto-friend

**Comment by GoldenNaim** [comment] 2020-11-19 08:32
It works fine for me with this code : 

```python
from decimal import Decimal
from cryptofeed import FeedHandler
from cryptofeed.callback import LiquidationCallback, OpenInterestCallback, TradeCallback 
from cryptofeed.defines import BID, ASK, LIQUIDATIONS, OPEN_INTEREST, TRADES
from cryptofeed.exchanges import BinanceFutures
from cryptofeed.pairs import binance_futures_pairs


async def oi(feed, pair, open_interest, timestamp, receipt_timestamp):
    print(f'Timestamp: {timestamp} Feed: {feed} Pair: {pair} open interest: {open_interest}')

def main():
    f = FeedHandler()
    f.add_feed(BinanceFutures(pairs=binance_futures_pairs(), channels=[OPEN_INTEREST], callbacks={OPEN_INTEREST: OpenInterestCallback(oi)}))
    f.run()

if __name__ == '__main__':
    main()
```

**Comment by OnlyC** [comment] 2020-11-19 08:40
Please try with 4 channels: TRADES, L2_BOOK, OPEN_INTEREST, LIQUIDATIONS

**Comment by GoldenNaim** [comment] 2020-11-19 08:46
Okay, it seems the bug it's only with the LiquidationCallback

**Comment by OnlyC** [comment] 2020-11-19 08:56
try with 3 channels also freeze [TRADES, L2_BOOK, TICKER]
74 pairs * 3 = 222 streams > 200 streams limit.

**Comment by GoldenNaim** [comment] 2020-11-19 09:08
But works fine with :  channels=[OPEN_INTEREST, TRADES, L2_BOOK] .

I think the problem is not here

**Comment by OnlyC** [comment] 2020-11-19 09:10
The OPEN_INTEREST is not a stream, it's a restAPI call.

**Comment by GoldenNaim** [comment] 2020-11-19 09:12
You have right, I will try something to see if it works, 5min.

**Comment by GoldenNaim** [comment] 2020-11-19 09:19
Okay so, the Binance documentation say :  The maximum stream number **that a single connection can listen** to changes as 200.

So this solution work fine for me ( tested ) : 
```python
def main():
    f = FeedHandler()
    f.add_feed(BinanceFutures(pairs=binance_futures_pairs(), channels=[OPEN_INTEREST, TRADES, L2_BOOK], callbacks={OPEN_INTEREST: OpenInterestCallback(oi), TRADES: TradeCallback(trade), L2_BOOK: BookCallback(book)}))
    f.add_feed(BinanceFutures(pairs=binance_futures_pairs(), channels=[LIQUIDATIONS], callbacks={LIQUIDATIONS: LiquidationCallback(liquidations)}))
    f.add_feed(BinanceFutures(pairs=binance_futures_pairs(), channels=[TICKER], callbacks={TICKER: TickerCallback(ticker)}))
    f.run()
```

**Comment by OnlyC** [comment] 2020-11-19 09:23
Ahh, nice. Thank you!

**Comment by OnlyC** [comment] 2020-11-19 09:24
Then this issues shouldn't tag as a bug, I can't change it.

**Comment by bmoscon** [comment] 2020-11-19 12:12
so I'm confused - is there an issue still or not?

**Comment by OnlyC** [comment] 2020-11-19 12:22
Yes, there is an issue with Binance that we can't use 1 feed connection to stream all the pairs but we can with more feeds.
I think a notice in the docs will do the job.

**Comment by bmoscon** [comment] 2020-11-19 13:52
let me see if its possible to get something working in the code that solves this.

**Comment by davidtwomey** [comment] 2020-11-28 13:58
@bmoscon note this also affects Binance spot (`BINANCE`), as well as `BINANCE_FUTURES`

BINANCE (Spot) [docs](https://binance-docs.github.io/apidocs/spot/en/#limits) under websocket limits: 
> "A single connection can listen to a maximum of 1024 streams"

BINANCE (Futures) [docs](https://binance-docs.github.io/apidocs/futures/en/#websocket-market-streams) 
> "The maximum stream number that a single connection can listen to changes as 200."
(also shows up in change log on the same page for 2020-Oct-27)

Note: this only appears in the tether USDT margined futures but not the COIN margin futures...but suspect the limit probably exists on both.

If i can find some time i will test empircally, but just from a quick test Binance SPOT TRADES channel seems to hit a limit when trying to subscribe to 965 symbols. However, the Binance SPOT TICKER channel does not...:sigh

**Comment by bmoscon** [comment] 2020-12-14 22:10
I have a fix for this, but it will require waiting until I've rolled out my update to the connection architecture to allow exchanges to connect on more than one websocket. Probably another week or two

**Comment by bmoscon** [comment] 2020-12-25 00:03
this has been fixed!

**Closed by bmoscon** 2020-12-25 00:03 UTC
Labels: bug
