### ISSUE TITLE
Poloniex trades problem

### ISSUE THREAD

**Issue by nateGeorge** [bmoscon/cryptofeed#130] opened 2019-07-31 17:13 UTC
Getting the trades from Poloniex using cryptostore for BTC-USDT and ETH-USDT (with or without backfill) with Redis and Arctic results in the following error:

```python
2019-07-31 11:12:05,238 : WARNING : POLONIEX: missing sequence number. Received 2, expected 396666720
2019-07-31 11:12:05,238 : ERROR : POLONIEX: error handling message [149,2]
2019-07-31 11:12:05,353 : ERROR : POLONIEX: encountered an exception, reconnecting
Traceback (most recent call last):
  File "/home/nate/anaconda3/lib/python3.6/site-packages/cryptofeed-1.0.0-py3.6.egg/cryptofeed/feedhandler.py", line 174, in _connect
    await self._handler(websocket, feed.message_handler, feed.id)
  File "/home/nate/anaconda3/lib/python3.6/site-packages/cryptofeed-1.0.0-py3.6.egg/cryptofeed/feedhandler.py", line 193, in _handler
    await handler(message, self.last_msg[feed_id])
  File "/home/nate/anaconda3/lib/python3.6/site-packages/cryptofeed-1.0.0-py3.6.egg/cryptofeed/poloniex/poloniex.py", line 176, in message_handler
    raise MissingSequenceNumber
cryptofeed.exceptions.MissingSequenceNumber
```

**Comment by bmoscon** [comment] 2019-07-31 17:29
Believe I fixed this last night, not sure what version of the code you are on. Can you send me the specific config for poloniex (symbols, channels, etc?)

**Comment by nateGeorge** [comment] 2019-07-31 18:53
NIce, it seems to be working now.  Looks like the backfill isn't working due to a timestamp conversion, but I'll open an issue in cryptostore for that since it's in that code.

**Comment by xiandong79** [comment] 2019-08-01 02:33
> NIce, it seems to be working now. Looks like the backfill isn't working due to a timestamp conversion, but I'll open an issue in cryptostore for that since it's in that code.

@nateGeorge have you tested Poloniex with the latest code from Github of cryptofeed and cryptostore ?

I got errors.

**Comment by nateGeorge** [comment] 2019-08-02 04:13
Yes, I believe it works with the latest versions from github.  I'm running it currently.

**Comment by zerzer04** [comment] 2019-10-12 16:59
I am getting this as well . The cause is **"i"** message which appears sometimes after the initial dump of the book: see note in [https://docs.poloniex.com/#price-aggregated-book](https://docs.poloniex.com/#price-aggregated-book)

changing: "elif self.seq_no[chan_id] + 1 != seq_no" -> " elif self.seq_no[chan_id] + 1 != seq_no **and msg[2][0][0]!='i'** " in async def message_handler function of poloniex.py could be a solution

**Comment by nateGeorge** [comment] 2019-10-16 14:51
Ah yeah, I'm still getting this too.  I think you are right.  Here's the error I'm seeing:

```python
2019-10-16 08:46:33,633 : WARNING : POLONIEX: missing sequence number. Received 474821731, expected 474821605                2019-10-16 08:46:33,633 : ERROR : POLONIEXbf943381-7cd8-4412-92d5-15e7714068f3: error handling message [121,474821731,[["i",{"currencyPair":"USDT_BTC","orderBook":[{"7967.91372979":"0.08085059" (entire order book follows)
```

**Comment by bmoscon** [comment] 2019-10-18 00:49
the code handles `i` messages. The error you're seeing there is because of the missing sequence number. Its expecting one, but got another. The fact that the `i` message triggered it is just a coincidence. Exchanges can have missing messages, there isnt anything to 'fix' here, the feed handler will reconnect (but it will report the error).

**Comment by nateGeorge** [comment] 2019-10-18 03:22
Ok, the weird thing is when I implement zerzer's change, it doesn't seem to have to reconnect, maybe because it's not raising an error. The missing sequence number seems to happen very frequently with poloniex...like on a regular basis.  It's not the best because it dumps the whole order book to the console and makes it hard to scroll up in the console.

**Comment by bmoscon** [comment] 2019-10-18 13:26
@nateGeorge so it looks like I can do a few things here:

* I can make it so the messages that trigger exceptions are only reported when enabled - this would be a flag to the feedhandler so the long messages wont fill the screen/log files
* Poloniex docs indicate that the `i` message requires a book reset, but I don't have to reset the connection, the data to reset the book is in the message, so I can tweak the code to ignore missing sequence numbers when its an `i` update and reset the book from that message

**Comment by nateGeorge** [comment] 2019-10-18 14:29
I think both of those sound like great ideas.

**Comment by bmoscon** [comment] 2019-10-18 16:50
@nateGeorge first part is done, messages are disabled by default on exceptions.

**Comment by bmoscon** [comment] 2019-10-22 12:04
should be fixed now, I ran for 2 days and never reproduced the problem, but the code is in there should it happen again - let me know

**Closed by bmoscon** 2019-10-22 12:04 UTC

**Comment by nateGeorge** [comment] 2019-10-24 23:18
Yes, seems to be working now, thanks!
