### ISSUE TITLE
Bybit - error in BTC-USDT pair

### ISSUE THREAD

**Issue by yohplala** [bmoscon/cryptofeed#343] opened 2020-12-03 07:57 UTC
**Describe the bug**
With following config file.
```yaml
    BYBIT:
        channel_timeouts:
            trades: 90
            l2_book: 90
        retries: -1
        trades: [BTC-USDT,BTC-USD]
        l2_book:
            symbols: [BTC-USDT,BTC-USD]
            book_delta: true
            book_interval: 100000
```

I got following error (running from Cryptostore).
```yaml
2020-12-03 08:48:27,257 : ERROR : BYBIT: Error from exchange {'success': False, 'ret_msg': 'error:invalid filter:BTCUSDT', 'conn_id': '7c94d1fe-ff93-4ba6-b8f3-7c800620e31a', 'request': {'op': 'subscribe', 'args': ['orderBookL2_25.BTCUSDT']}}
2020-12-03 08:48:27,381 : ERROR : BYBIT: Error from exchange {'success': False, 'ret_msg': 'error:invalid filter:BTCUSDT', 'conn_id': 'f5dd166f-a839-4880-9340-3cc931f5b306', 'request': {'op': 'subscribe', 'args': ['trade.BTCUSDT']}}
```

**Expected behavior**
Well, if channel or pair, either of them is not known, the usual error message indicating they are not known.
But I run `info()` method and they both appear to be ok.

```python
Bybit.info()
Out[2]: 
{'pairs': ['BTC-USD',
  'ETH-USD',
  'EOS-USD',
  'XRP-USD',
  'BTC-USDT',
  'ETH-USDT',
  'LTC-USDT',
  'XTZ-USDT',
  'LINK-USDT'],
 'channels': ['futures_index', 'l2_book', 'open_interest', 'trades'],
 'tick_size': {'BTC-USD': '0.5',
  'ETH-USD': '0.05',
  'EOS-USD': '0.001',
  'XRP-USD': '0.0001',
  'BTC-USDT': '0.5',
  'ETH-USDT': '0.05',
  'LTC-USDT': '0.01',
  'XTZ-USDT': '0.001',
  'LINK-USDT': '0.001'}}
```

**Operating System:**
Ubuntu 18.04

**Cryptofeed Version**
1.6.2

**Comment by bmoscon** [comment] 2020-12-04 00:30
as best I can tell this is an issue with BYBIT. The trading pair is still listed/active, no notices have been posted about any change to their supported pairs, and other symbols still work. I re-verified the API is being used correctly, and confirmed other symbols do work. Doesn't look like anything I can do

**Comment by bmoscon** [comment] 2020-12-05 00:31
Also, I tried to reach out to support but you have to have an account to do so.

**Comment by yohplala** [comment] 2020-12-05 07:23
Hi @bmoscon , I have sent them an email, and started to discuss that by chat. They are looking into it. I will let you know as soon as I have a feedback!
Thanks for your very reactive support Bryant!

**Comment by yohplala** [comment] 2020-12-05 07:25
The error message seems related to the way we call the pair/channel.
I wanted to have a look to the response returned by the url used to generate the list of pairs, but haven't had the time yet.

**Comment by yohplala** [comment] 2020-12-05 11:41
@bmoscon, support answer is not crystal clear to me, but it gives a direction.
They basically tell me the following before redirecting to the documentation page:
_The relevant team confirmed that the Inverse and USDT pairs API are different. Please feel free to visit this link for reference:
https://bybit-exchange.github.io/docs/linear/#t-websocketorderbook25_

While I am not sure the link provided does help us, they also enclose a screenshot showing 2 documentations:
- one for "[Inverse Perpetual](https://bybit-exchange.github.io/docs/inverse/#t-websocket)" (USD pairs), which endpoint appears to be one of the following
```
Mainnet(both endpoints are available):
wss://stream.bybit.com/realtime 
wss://stream.bytick.com/realtime 
```
- one for "[USDT Perpetual](https://bybit-exchange.github.io/docs/linear/#t-websocket)" (USDT pairs), which endpoint appears to be one of the following
```
Mainnet public(both endpoints are available):
wss://stream.bybit.com/realtime_public 
wss://stream.bytick.com/realtime_public 
Mainnet private(both endpoints are available):
wss://stream.bybit.com/realtime_private 
wss://stream.bytick.com/realtime_private 
```

So possibly (I did not have a look), does cryptofeed dissociate endpoints given the pair?

After this, the request command does seem to be actually the same for both type of pairs.
- Inverse Perpetual (USD pair)
`ws.send('{"op":"subscribe","args":["trade.BTCUSD"]}')`
- USDT Perpetual (USDT pair)   -> **they call 'USDT' actually 'USD'**: this may be the trick (at least, it is what shows their example.
`ws.send('{"op":"subscribe","args":["trade.BTCUSD"]}')`


Hope this can help.
Bests,

**Comment by yohplala** [comment] 2020-12-05 11:45
Beetween, I am surprised **l2_book** only takes **l2_25** and not **l2_200**. Is it common in Cryptofeed?

**Comment by bmoscon** [comment] 2020-12-05 20:54
the L2_200 feed is not realtime, its only ever 100ms. Since the L2_25 is realtime, that is preferred.

**Comment by bmoscon** [comment] 2020-12-05 20:58
it looks like they have a websocket address for USDT pairs and one for USD pairs, but they share the same rest API for querying trading pairs. I'll need to make an architecture change to cryptofeed to support multiple websocket connections per exchange/feed. Its not terribly hard to do, I've just been putting it off. Its needed for authenticated channels too. I have a design/plan, going to start on it this weekend.

**Comment by yohplala** [comment] 2020-12-05 21:03
> the L2_200 feed is not realtime, its only every 100ms. Since the L2_25 is realtime, that is preferred.

aaahhh, when user's need differ... I am more interested in having more complete view of the ob, and would be fine with 100ms refreshment (anyway, I am building a view of the ob only every minute).
Is there any 'keyword' to allow the user to chose?

Actually, there is one in cryptostore `max_depth`.
Is there any way (maybe on cryptostore's side then) that if `max_depth` <26, then l2_25 is used in cryptofeed, and if max_depth > 25 or not specified, then l2_200 is used?

**Comment by bmoscon** [comment] 2020-12-06 01:00
There is no support for changing between things like this in either cryptofeed or cryptostore

**Comment by bmoscon** [comment] 2020-12-14 22:06
I'm working on an update to the connection architecture in cryptofeed that will allow an exchange to have multiple websocket connections open (for things like this, as well as for authenticated feeds)

**Comment by yohplala** [comment] 2020-12-15 06:40
hi @bmoscon 
ok great,
also for Binance that limits number of symbol for one websocket? (meaning a same websocket can be opened several times? or are there necessarily different websockets?)

**Comment by bmoscon** [comment] 2020-12-24 22:53
fixed now that exchanges can create multiple websocket connections!

**Closed by bmoscon** 2020-12-24 22:53 UTC
Labels: bug
